# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8358c3c2d68b38104a9de94448f6bc1c42d89c43e6eafdcab74f7d4f50d113b9b836c9bb748709487db5c83dc652a9129eaaafe93454ea2209c9efd8727291ef

test:
  secret_key_base: 0b6ae8ba026027a2289a21a0447fd162dfc7a898dc53138c0b544fa8ff7d17915b2b9d3410303a4d11bd8a314652158b15f1e379705414a32efafe8486704075

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
